name: Docker Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    runs-on: docker
    container:
      image: docker:27-dind
      options: --privileged
    steps:
      - name: Checkout code
        run: |
          apk add --no-cache git
          git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .
          git checkout ${{ gitea.sha }}

      - name: Start Docker daemon
        run: |
          dockerd-entrypoint.sh &
          sleep 5
          docker info

      - name: Extract metadata
        id: meta
        run: |
          BRANCH_NAME=$(echo ${{ gitea.ref_name }} | sed 's/\//-/g')
          SHORT_SHA=$(echo ${{ gitea.sha }} | cut -c1-7)
          echo "image_tag=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ gitea.repository }}:${{ steps.meta.outputs.image_tag }} \
            --tag ${{ gitea.repository }}:latest \
            --label "org.opencontainers.image.created=${{ steps.meta.outputs.build_date }}" \
            --label "org.opencontainers.image.revision=${{ gitea.sha }}" \
            --label "org.opencontainers.image.source=${{ gitea.server_url }}/${{ gitea.repository }}" \
            .

      - name: List built images
        run: docker images | grep "${{ gitea.repository }}"
